"""
Regulayer Decision Recorder - Data Models

Canonical schemas matching SDK DecisionEvent with additional record fields.
"""

from datetime import datetime
from typing import Optional, List, Literal, Union
from pydantic import BaseModel, Field, field_validator
from uuid import UUID
from regulayer_attestation.app.models import AttestationEnvelope


class RuntimeFingerprint(BaseModel):
    """Runtime environment fingerprint (matches SDK)."""
    
    python_version: str
    os: str
    sdk_version: str
    sdk_instance_id: str
    
    class Config:
        frozen = True
        extra = "forbid"


class DecisionEvent(BaseModel):
    """
    Decision event from SDK (input validation model).
    
    This MUST match the SDK's DecisionEvent exactly.
    """
    
    # Event metadata
    event_version: str
    event_state: Literal["completed", "failed"]
    
    # Decision identification
    decision_id: UUID
    system_name: str
    risk_level: str
    
    # Model information
    model_name: str
    model_version: str
    
    # Data hashes
    input_hash: Optional[str] = None
    output_hash: Optional[str] = None
    prompt_hash: Optional[str] = None
    tool_calls_hashes: Optional[List[str]] = None
    
    # Timing
    start_timestamp: datetime
    end_timestamp: datetime
    execution_duration_ms: float
    
    # Runtime environment
    runtime_fingerprint: RuntimeFingerprint
    
    # Ordering (Optional for legacy/unstrict, required for strict projects)
    sequence_number: Optional[int] = None
    
    @field_validator('input_hash', 'output_hash', 'prompt_hash')
    @classmethod
    def validate_hash(cls, v: Optional[str]) -> Optional[str]:
        """Validate SHA-256 hash format."""
        if v is not None:
            if len(v) != 64:
                raise ValueError("Hash must be 64 characters (SHA-256)")
            if not all(c in '0123456789abcdef' for c in v.lower()):
                raise ValueError("Hash must be hexadecimal")
        return v
    
    @field_validator('tool_calls_hashes')
    @classmethod
    def validate_tool_calls_hashes(cls, v: Optional[List[str]]) -> Optional[List[str]]:
        """Validate all tool call hashes."""
        if v is not None:
            for h in v:
                if len(h) != 64 or not all(c in '0123456789abcdef' for c in h.lower()):
                    raise ValueError("Tool call hash must be 64-character hex")
        return v
    
    class Config:
        frozen = True
        extra = "forbid"  # No unknown fields allowed


class IngestRequest(BaseModel):
    """
    Ingestion request wrapper.
    
    Discriminated union to strictly separate legacy vs attested events.
    """
    ingestion_type: Literal["legacy", "attested"]
    payload: Union[DecisionEvent, AttestationEnvelope]


class AttestationSummary(BaseModel):
    """Summary of cryptographic attestation for a record."""
    identity_id: UUID
    algorithm: str
    signed_at: datetime
    identity_status_at_signing: Literal["active", "revoked_after"]


class DecisionRecord(BaseModel):
    """
    Decision record (stored format with chain fields).
    
    This extends DecisionEvent with recorder-generated fields.
    """
    
    # Record metadata (generated by recorder)
    record_id: int
    record_hash: str  # SHA-256 of canonical_payload
    previous_record_hash: Optional[str]  # NULL for first record
    canonical_payload: dict  # Deterministically serialized event
    canonical_payload_hash: str  # Optimization for fast verification
    chain_id: str = "global"  # Constant in Phase 1
    sequence_number: Optional[int] = None  # Position in the chain (per-project)
    server_timestamp: datetime
    
    # Original event data (flattened for easy querying)
    decision_id: UUID
    sdk_instance_id: UUID
    system_name: str
    risk_level: str
    event_state: str
    sdk_version: str
    
    # Attestation (Phase 2.2+)
    attestation: Optional[AttestationSummary] = None
    
    class Config:
        frozen = True
        extra = "forbid"


class VerificationMetadata(BaseModel):
    """Context about who verified the export and when."""
    verified_at: datetime
    verifier_version: str
    recorder_version: str
    verification_result: Literal["VALID", "INVALID"]



class ProofAttestation(BaseModel):
    """Full attestation for proof bundles."""
    identity_id: UUID
    public_key: str
    algorithm: str
    signed_at: datetime
    signature: str

class ExportBundle(BaseModel):
    """
    Self-contained forensic proof bundle.
    
    Contains everything needed to verify the decision offline.
    """
    proof_bundle_version: str = "1.0.0"
    record_id: int
    canonical_event: dict
    attestation: Optional[ProofAttestation]
    record_hash: str
    previous_record_hash: Optional[str]
    chain_id: str
    server_timestamp: datetime
    verification_metadata: VerificationMetadata


class RecordConfirmation(BaseModel):
    """Response returned when a decision is successfully recorded."""
    
    record_id: int
    decision_id: UUID
    record_hash: str
    server_timestamp: datetime


    server_timestamp: datetime


class ChainStatus(BaseModel):
    chain_id: str
    total_records: int
    first_record_timestamp: Optional[datetime] = None
    last_record_timestamp: Optional[datetime] = None
    integrity_status: Literal["PASS", "FAIL", "UNKNOWN"]
    failure_reason: Optional[str] = None


class VerificationResult(BaseModel):
    is_valid: bool
    total_records_checked: int
    broken_at_record_id: Optional[int] = None
    verification_duration_ms: float
    errors: List[str]
    # Phase 2.3 additions
    attested_records_count: int = 0
    legacy_records_count: int = 0
    revoked_records_count: int = 0



class ChainStatus(BaseModel):
    chain_id: str
    total_records: int
    first_record_timestamp: Optional[datetime] = None
    last_record_timestamp: Optional[datetime] = None
    integrity_status: Literal["PASS", "FAIL", "UNKNOWN"]
    failure_reason: Optional[str] = None


class VerificationResult(BaseModel):
    is_valid: bool
    total_records_checked: int
    broken_at_record_id: Optional[int] = None
    verification_duration_ms: float
    errors: List[str]
    # Phase 2.3 additions
    attested_records_count: int = 0
    legacy_records_count: int = 0
    revoked_records_count: int = 0


class HealthStatus(BaseModel):
    """Health check response."""
    
    status: Literal["healthy", "degraded"]
    database_reachable: bool
    chain_writable: bool
    last_record_timestamp: Optional[datetime] = None
    total_records: int = 0


class ErrorResponse(BaseModel):
    """Error response format."""
    
    error: str  # Error class name
    message: str
    decision_id: Optional[UUID] = None


