"""
Regulayer Reports - Legal Disclaimers

MANDATORY: Every report must include these disclaimers.
These establish the legal boundaries of what reports prove.
"""

import hashlib
from typing import List


# Core disclaimer that must appear on every report
CORE_DISCLAIMER = """
This document proves record integrity and authorship only.
It does not attest to AI correctness, fairness, legality, or compliance.
"""

# Extended disclaimers by report type
SYSTEM_REPORT_DISCLAIMERS = [
    CORE_DISCLAIMER.strip(),
    "This report describes system architecture, not operational status.",
    "Trust guarantees depend on correct deployment and key custody.",
    "No guarantee of system availability or uptime is made.",
    "Cryptographic algorithms may become obsolete; verify current standards.",
]

DECISION_REPORT_DISCLAIMERS = [
    CORE_DISCLAIMER.strip(),
    "This report proves the decision was recorded, not that it was correct.",
    "AI decisions may be biased, unfair, or incorrect regardless of integrity.",
    "Governance metadata is organizational process, not authoritative fact.",
    "Verify proof bundle independently using regulayer-proof-verifier.",
]

CHAIN_REPORT_DISCLAIMERS = [
    CORE_DISCLAIMER.strip(),
    "Chain integrity does not imply correctness of recorded decisions.",
    "A broken chain indicates tampering but not the nature of tampering.",
    "Gap detection is based on record IDs; missing records are flagged.",
]


def get_disclaimers(report_type: str) -> List[str]:
    """Get disclaimers for a report type."""
    if report_type == "system":
        return SYSTEM_REPORT_DISCLAIMERS
    elif report_type == "decision":
        return DECISION_REPORT_DISCLAIMERS
    elif report_type == "chain":
        return CHAIN_REPORT_DISCLAIMERS
    else:
        return [CORE_DISCLAIMER.strip()]


def get_disclaimer_hash(disclaimers: List[str]) -> str:
    """Compute SHA-256 hash of disclaimers for integrity verification."""
    combined = "\n".join(disclaimers)
    return hashlib.sha256(combined.encode()).hexdigest()


# Footer text for PDF reports
PDF_FOOTER = (
    "STATIC REPORT — This document is a snapshot and does not reflect live system state. "
    "Generated by Regulayer Reports v1.0.0"
)

# Watermark text
PDF_WATERMARK = "STATIC REPORT"
